import scrapy

class ProductItem(scrapy.Item):
    ref_product_url = scrapy.Field()
    ref_product_id = scrapy.Field()
    ref_variant_id = scrapy.Field()
    ref_category = scrapy.Field()
    ref_category_url = scrapy.Field()
    ref_brand_name = scrapy.Field()
    ref_product_name = scrapy.Field()
    ref_sku = scrapy.Field()
    ref_mpn = scrapy.Field()
    ref_gtin = scrapy.Field()
    ref_price = scrapy.Field()
    ref_main_image = scrapy.Field()
    ref_quantity = scrapy.Field()
    ref_group_attr1 = scrapy.Field()
    ref_group_attr2 = scrapy.Field()
    ref_status = scrapy.Field()
    date_scrapped = scrapy.Field()